/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class AppStorageConstant {

  public static readonly CRED_CONNECTION_DOMAIN: string = 'CRED_CONNECTION_DOMAIN';
  public static readonly CRED_CONNECTION_DOMAIN_NUM: string = 'CRED_CONNECTION_DOMAIN_NUM';

  public static readonly DOMAIN_ACCOUNT_MAP: string = 'DOMAIN_ACCOUNT_MAP';

  public static readonly ACCOUNT_VERIFY_SUCCESS_COUNT: string = 'hiAccountVerifySucc';
  public static readonly ACCOUNT_VERIFY_FAIL_COUNT: string = 'hiAccountVerifyFail';



}
