/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  public static INDEX_BORDER_RADIUS = 24;
  public static FOOTER_HEIGHT = 40;
  public static FOOTER_BUTTON_HEIGHT = 40;
  public static FOOTER_ROW_WIDTH = '100%';
  public static FOOTER_ROW_MARGIN = 8;
  public static FOOTER_ROW_PAD_LEFT = 16;
  public static FOOTER_ROW_PAD_RIGHT = 16;
  public static HEADER_TEXT_FRONT_SIZE = 20;
  public static HEADER_TEXT_LINE_HEIGHT = 28;
  public static HEADER_TEXT_WIDTH = '100%';
  public static HEADER_COLUMN_WIDTH = '100%';
  public static HEADER_COLUMN_HEIGHT = 56;
  public static HEADER_COLUMN_HEIGHT_READONLY = 40;
  public static HEADER_COLUMN_PADDING_LEFT = 24;
  public static HEADER_COLUMN_PADDING_RIGHT = 24;
  public static HEADER_COLUMN_PADDING_BOTTOM = 24;
  public static HEADER_COLUMN_MARGIN_BOTTOM = 4;
  public static FOOTER_WIDTH_BUTTON = '48%';
  public static ENCRYPTION_SUCCESS_CIRCLE = 64;
  public static ENCRYPTION_SUCCESS_ICON = 40;
  public static HEADER_COLUMN_MESSAGE_TIPS = 400;
  public static HEADER_COLUMN_MESSAGE_TIPS_CLOUD = 242;
  public static ENCRYPTION_SUCCESS_TRANSLATE = 180;
  public static ENCRYPTION_SUCCESS_TRANSLATE_WIDTH = 180;
  public static ENCRYPTION_SUCCESS_CHANGE_TOP = 32;
  public static ENCRYPTION_ADD_STAFF_WIDTH = 110;
  public static ENCRYPTION_LOADING_HEIGHT = 340;
  public static ENCRYPTION_LOADING_ICON_HEIGHT = 72;
  public static ENCRYPTION_LOADING_CONTENT_HEIGHT = '65%';
  public static HEADER_ROW_FONT_SIZE = 16;
  public static ENCRYPTION_STAFF_BORDER_RADIUS = 999;
  public static ENCRYPTION_STAFF_MAX_WIDTH = 82;
  public static ENCRYPTION_STAFF_WIDTH = 112;
  public static ENCRYPTION_STAFF_WIDTH_NAME = 82;
  public static ENCRYPTION_STAFF_PAD = 8;
  public static ENCRYPTION_PERMISSION_STATUS_WIDTH = '70%';
  public static ENCRYPTION_PERMISSION_STATUS_IMAGE = '90%';
  public static PP_TEXT_MAX_LINE = 1;
  public static MAIN_FLAG_MAX_NUMBER = 1;
  public static PP_TEXT_PAD_RIGHT = 4;
  public static PP_IMAGE_WIDTH = 24;
  public static PP_IMAGE_HEIGHT = 24;
  public static PP_IMAGE_PAD = 2;
  public static PP_TEXT_FONT_SIZE2 = 12;
  public static PP_TEXT_LINE_HEIGHT2 = 17;
  public static PP_BUTTON_PAD = 0;
  public static PP_ROW_RADIUS = 0;
  public static AP_TEXT_PAD_RIGHT = 4;
  public static AP_MARGIN_TOP = 19;
  public static DU_WIDTH_FULL = '100%';
  public static DU_LINE_WIDTH = 0.5;
  public static DU_LINE_MARGIN_TOP2 = 8;
  public static DA_FONT_SIZE = 20;
  public static DA_ROW_HEIGHT = 56;
  public static DA_ROW_WIDTH = 288;
  public static DA_TEXT_LINE_HEIGHT = 28;
  public static DA_SCROLL_LINE_HEIGHT = 16;
  public static DA_SCROLL_FONT_SIZE = 14;
  public static DA_SCROLL_BAR_WIDTH = 5;
  public static DA_STRAIN_SIZE_MA_HEIGHT = 500;
  public static DA_MARGIN_TOP = 12;
  public static DA_SCROLL_WIDTH = 288;
  public static ROW_BUTTON_WIDTH = 304;
  public static ROW_BUTTON_HEIGHT = 40;
  public static ROW_FONT_SIZE = 16;
  public static ROW_MARGIN_TOP = 8;
  public static DA_COLOUM_WIDTH = 336;
  public static DA_COLOUM_RADIUS = 24;

  public static FILE_OPEN_HISTORY_ZERO = 0;
  public static FILE_OPEN_HISTORY_ONE = 1;
  public static FILE_OPEN_HISTORY_TWO = 2;
  public static FILE_OPEN_HISTORY_THREE = 3;
  public static FILE_OPEN_HISTORY_FOUR = 4;
  public static ADD_STAFF_ITEM_MARGIN_RIGHT = 4;
  public static CHANGE_MAX_HEIGHT = '70%';
  public static ENCRYPTION_SUCCESS_MAX_HEIGHT = '70%';
  public static ENCRYPTION_SUCCESS_ROTATE_MARGIN_BOTTOM = 16;
  public static ENCRYPTION_SUCCESS_IMAGE_MARGIN_TOP = 16;
  public static ENCRYPTION_SUCCESS_ADD_STAFF_MARGIN_TOP = 12;
  public static ENCRYPTION_SUCCESS_ADD_STAFF_MARGIN_BOTTOM = 16;
  public static ENCRYPTION_READ_ONLY_EDIT_HEIGHT = 19;
  public static ENCRYPTION_CHANGE_TIPS_MARGIN_BOTTOM = 16;
  public static ENCRYPTION_CHANGE_VALID_UNTIL_MARGIN_BOTTOM = 8;
  public static ENCRYPTION_BUTTON_PADDING_TOP = 16;
  public static ENCRYPTION_BUTTON_MARGIN_BOTTOM = 24;
  public static ENCRYPTION_BUTTON_TO_BUTTON_WIDTH = 16;
  public static ENCRYPTION_STAFF_ITEM_MARGIN = 12;
  public static ENCRYPTION_STAFF_ITEM_MARGIN_BOTTOM = 12;
  public static ENCRYPTION_ADD_STAFF_HEIGHT = 28;
  public static ENCRYPTION_ADD_STAFF_PADDING_TOP = 10;
  public static ENCRYPTION_ADD_STAFF_BORDER = 1;
  public static ENCRYPTION_ADD_STAFF_BORDER2 = 2;
  public static ENCRYPTION_ADD_STAFF_BORDER_MARGIN_TOP = 8;
  public static ENCRYPTION_SUCCESS_TOGGLE_HEIGHT = 32;
  public static ENCRYPTION_PROTECTION_BUTTON_MARGIN = 8;
  public static ENCRYPTION_PROTECTION_TIME_MENU_HEIGHT = 50;
  public static ENCRYPTION_PROTECTION_TIME_MENU_PADDING_LEFT = 12;
  public static ENCRYPTION_PROTECTION_TIME_MENU_PADDING_RIGHT = 12;
  public static ENCRYPTION_PROTECTION_TIME_MENU_MARGIN_LEFT = 2;
  public static ENCRYPTION_PROTECTION_TIME_MENU_MARGIN_RIGHT = 2;
  public static ENCRYPTION_PROTECTION_TIME_MENU_DIVIDER_LENGTH = '76%';
  public static ENCRYPTION_PROTECTION_TIME_MENU_WIDTH = 32;
  public static ENCRYPTION_ADD_STAFF_FLEX_GROW = 1;
  public static ENCRYPTION_ADD_STAFF_MARGIN_RIGHT = 8;
  public static ENCRYPTION_ADD_STAFF_MARGIN_BOTTOM = 8;
  public static ENCRYPTION_ON_AREA_CHANGE_WIDTH = 0;
  public static ENCRYPTION_DOUBLED_NUMBER = 2;
  public static ENCRYPTION_SET_TIMEOUT_TIME = 20;
  public static ENCRYPTION_EMIT_DIRECTION_STATUS = 1;
  public static ENCRYPTION_ADD_STAFF_LENGTH_MAX = 50;
  public static ENCRYPTION_ADD_STAFF_LENGTH = 0.9;
  public static ENCRYPTION_STATUS_VALUE_COLOR = 0.6;
  public static ENCRYPTION_TYPE_SELECT_INDEX = 0;
  public static ENCRYPTION_TYPE_SELECT = 1;
  public static ENCRYPTION_ADD_STAFF_MENU_WIDTH = 100;
  public static ENCRYPTION_ADD_STAFF_MENU_HEIGHT = 50;
  public static ENCRYPTION_MESSAGE_DIALOG_TIPS = 400;
  public static ENCRYPTION_MESSAGE_DIALOG_BUTTON = 256;
  public static ENCRYPTION_MESSAGE_DIALOG_TIPS_PADDING = 72;
  public static ENCRYPTION_MESSAGE_ALERT_MESSAGE_TOP = 0;
  public static ENCRYPTION_MESSAGE_ALERT_MESSAGE_TOP1 = 24;
  public static ENCRYPTION_MESSAGE_ALERT_MESSAGE_PADDING_LEFT = 24;
  public static ENCRYPTION_MESSAGE_ALERT_MESSAGE_PADDING_TOP = 16;
  public static ENCRYPTION_PC_FIXING_WIDTH = 588;
  public static ENCRYPTION_PC_FIXING_STATUS_WIDTH = 400;
  public static ENCRYPTION_PC_FIXING_MINWIDTH = 0;

  public static DLPRPC_SERVICE_PROXY_ERRCODE = 0;
  public static DLP_MANAGER_BUNDLE_NAME = 'com.ohos.dlpmanager';
  public static TRANSPARENT_GREY_BACKGROUND_COLOR = '#33182431';
  public static TRANSPARENT_BACKGROUND_COLOR = '#00000000';
  public static START_ABILITY_YNUMBER = 300;
  public static START_ABILITY_WINDOW_WIDTH = 492;
  public static START_ABILITY_BASIC_WIDTH = 350;
  public static START_ABILITY_MSG_HEIGHT_ROWS = 25;
  public static START_ABILITY_HEIGHT_DEFAULT1 = 165;
  public static START_ABILITY_HEIGHT_DEFAULT = 154;
  public static START_ABILITY_HEIGHT_ONE_ROWS = 174;
  public static START_ABILITY_HEIGHT_TWO_ROWS = 194;
  public static START_ABILITY_HEIGHT_THREE_ROWS = 214;
  public static START_ABILITY_HEIGHT_FOUR_ROWS = 240;
  public static START_ABILITY_MESSAGE_HEIGHT = '20%';
  public static START_ABILITY_MESSAGE_HEIGHT1 = '31%';
  public static START_ABILITY_MESSAGE_HEIGHT_ONE = '24%';
  public static START_ABILITY_MESSAGE_HEIGHT_TWO = '32%';
  public static START_ABILITY_MESSAGE_HEIGHT_THREE = '45%';
  public static START_ABILITY_MESSAGE_HEIGHT_FOUR = '52%';

  public static FOOTER_OPACITY_ONE = 1;
  public static FOOTER_OPACITY_SEPC = 0.6;
  public static FOOTER_OPACITY_MID = 0.5;
  public static readonly ERR_JS_APP_ACCOUNT_INFO = 0;
  public static readonly ERR_JS_APP_INSIDE_ERROR = 1;
  public static readonly ERR_JS_GET_ACCOUNT_ERROR = 2;
  public static readonly ERR_JS_APP_NO_ACCOUNT_ERROR = 3;
  public static readonly ERR_JS_APP_PARAM_ERROR = 4;
  public static readonly ERR_JS_APP_GET_FILE_ASSET_ERROR = 5;
  public static readonly ERR_JS_APP_OPEN_REJECTED = 6;
  public static readonly ERR_JS_APP_ENCRYPTION_REJECTED = 7;
  public static readonly ERR_JS_APP_SYSTEM_IS_AUTHENTICATED = 8;
  public static readonly ERR_JS_APP_NETWORK_INVALID = 9;
  public static readonly ERR_JS_APP_ENCRYPTING = 10;
  public static readonly ERR_JS_CREDENTIAL_TIMEOUT = 19100003;
  public static readonly ERR_JS_CREDENTIAL_SERVICE_ERROR = 19100004;
  public static readonly ERR_JS_CREDENTIAL_SERVER_ERROR = 19100005;
  public static readonly ERR_JS_NOT_DLP_FILE = 19100008;
  public static readonly ERR_JS_DLP_FILE_READ_ONLY = 19100010;
  public static readonly ERR_JS_USER_NO_PERMISSION = 19100013;
  public static readonly ERR_JS_ACCOUNT_NOT_LOGIN = 19100014;
  public static readonly ERR_JS_SYSTEM_NEED_TO_BE_UPGRADED = 19100015;
  public static readonly ERR_JS_NOT_AUTHORIZED_APPLICATION = 19100018;
  public static readonly ERR_JS_FILE_EXPIRATION = 19100019;
  public static readonly ERR_JS_OFFLINE = 19100020;
  public static ERR_JS_INVALID_PARAMETER = 12300002;
  public static ERR_JS_ACCOUNT_NOT_FOUND = 12300003;
  public static ERR_JS_NETWORK_INVALID = 12300013;
  public static DLP_FILE_PARSE_ERROR = 103;
  public static DLP_INSTALL_SANDBOX_SUCCESS = 202;
  public static DLP_GET_PARAMETERS_FAILED = 100;
  public static DLP_START_SANDBOX_ERROR = 105;
  public static DLP_START_SANDBOX_SUCCESS = 203;
  public static DLP_INSTALL_SANDBOX_ERROR = 104;
  public static ERR_JS_DLP_NOT_PROVIDED = 301;

  public static GUTTER = 0;
  public static XS_COLUMNS = 2;
  public static XS_SPAN = 2;
  public static XS_OFFSET = 0;
  public static SM_COLUMNS = 4;
  public static SM_SPAN = 4;
  public static SM_OFFSET = 0;
  public static MD_COLUMNS = 8;
  public static MD_SPAN = 8;
  public static MD_OFFSET = 0;
  public static LG_COLUMNS = 12;
  public static LG_SPAN = 8;
  public static LG_OFFSET = 2;

  public static DIALOG_GUTTER = 24;
  public static DIALOG_MARGIN = 16;
  public static DIALOG_MARGIN_VERTICAL = 12;
  public static DIALOG_MD_SPAN = 6;
  public static DIALOG_MD_OFFSET = 1;
  public static DIALOG_LG_SPAN = 6;
  public static DIALOG_LG_OFFSET = 3;
  public static FUSE_PATH = '/mnt/data/fuse/';
  public static RAND_START = 2;
  public static RAND_END = 18;
  public static BUNDLE_LEN = 20;

  public static DLP_ZIP_MAGIC = 0x04034b50;

  public static VALIDITY_IMAGE_WIDTH = 10;
  public static VALIDITY_IMAGE_HEIGHT = 40;
  public static VALIDITY_IMAGE_PADDING_RIGHT = 12;
  public static VALIDITY_IMAGE_PADDING_LEFT = 8;

  public static TIPS_HEIGHT_ITEM = 20;
  public static TIPS_COLON_WIDTH = 9;
  public static TIPS_STAFF_WIDTH = 82;
  public static TIPS_STAFF_MAX_WIDTH = 50;
  public static TIPS_SPACE_ZERO = '\u200B';
  public static TIPS_SPACE_EN = '\u2002';
  public static TIPS_SPACE_EM = '\u2003';
  public static TIPS_NAME_LENGTH = 2;
  public static LOAD_TYPE_CE = 1;

  public static ENTER_KEY_VALUE = '\n';
  public static ENCRYPTION_ADD_STAFF_NO_MARGIN = 0;
  public static RICH_EDITOR_MIN_HEIGHT = 48;
  public static RICH_EDITOR_FIRST = 1;
  public static POPUP_OFFSET_X = -20;
  public static SUB_HEADER_HEIGHT = 40;
  public static STAFF_FONT_SIZE = 10;
  public static STAFF_FONT_PADDING = 1;
}
