/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class Constants {
  public static FOOTER_ROW_WIDTH = '100%';
  public static FOOTER_ROW_MARGIN = 8;
  public static FOOTER_ROW_PAD_LEFT = 16;
  public static FOOTER_ROW_PAD_RIGHT = 16;
  public static HEADER_TEXT_WIDTH = '100%';
  public static HEADER_COLUMN_WIDTH = '100%';
  public static HEADER_COLUMN_HEIGHT = 56;
  public static HEADER_COLUMN_PADDING_LEFT = 24;
  public static HEADER_COLUMN_PADDING_RIGHT = 24;
  public static HEADER_COLUMN_PADDING_BOTTOM = 24;
  public static HEADER_COLUMN_MARGIN_BOTTOM = 4;
  public static FOOTER_WIDTH_BUTTON = '48%';
  public static ENCRYPTION_SUCCESS_CIRCLE = 64;
  public static ENCRYPTION_SUCCESS_ICON = 40;
  public static HEADER_COLUMN_MESSAGE_TIPS = 400;
  public static ENCRYPTION_SUCCESS_TRANSLATE = 180;
  public static ENCRYPTION_SUCCESS_CHANGE_TOP = 32;
  public static ENCRYPTION_LOADING_HEIGHT = 340;
  public static ENCRYPTION_LOADING_ICON_HEIGHT = 72;
  public static ENCRYPTION_LOADING_CONTENT_HEIGHT = '65%';
  public static HEADER_ROW_FONT_SIZE = 16;
  public static ENCRYPTION_STAFF_BORDER_RADIUS = 999;
  public static ENCRYPTION_STAFF_WIDTH_NAME = 82;
  public static ENCRYPTION_STAFF_PAD = 8;
  public static ENCRYPTION_PERMISSION_STATUS_WIDTH = '70%';
  public static PP_TEXT_MAX_LINE = 1;
  public static PP_IMAGE_WIDTH = 24;
  public static PP_IMAGE_HEIGHT = 24;
  public static PP_IMAGE_PAD = 2;
  public static PP_TEXT_LINE_HEIGHT2 = 17;
  public static PP_BUTTON_PAD = 0;
  public static PP_ROW_RADIUS = 0;
  public static AP_TEXT_PAD_RIGHT = 4;
  public static AP_TEXT_PAD_LEFT = 0;
  public static DU_WIDTH_FULL = '100%';
  public static DU_LINE_WIDTH = 0.5;
  public static DU_LINE_MARGIN_TOP2 = 8;
  public static DA_ROW_HEIGHT = 56;
  public static DA_TEXT_LINE_HEIGHT = 28;
  public static DA_MARGIN_TOP = 12;
  public static ROW_FONT_SIZE = 16;

  public static FILE_OPEN_HISTORY_ZERO = 0;
  public static FILE_OPEN_HISTORY_ONE = 1;
  public static FILE_OPEN_HISTORY_TWO = 2;
  public static FILE_OPEN_HISTORY_THREE = 3;
  public static ADD_STAFF_ITEM_MARGIN_RIGHT = 4;
  public static ADD_STAFF_ITEM_MARGIN_LEFT = 0;
  public static CHANGE_MAX_HEIGHT = '70%';
  public static ENCRYPTION_SUCCESS_MAX_HEIGHT = '70%';
  public static ENCRYPTION_SUCCESS_ROTATE_MARGIN_BOTTOM = 16;
  public static ENCRYPTION_SUCCESS_IMAGE_MARGIN_TOP = 16;
  public static ENCRYPTION_SUCCESS_ADD_STAFF_MARGIN_TOP = 12;
  public static ENCRYPTION_SUCCESS_ADD_STAFF_MARGIN_BOTTOM = 16;
  public static ENCRYPTION_CHANGE_TIPS_MARGIN_BOTTOM = 16;
  public static ENCRYPTION_CHANGE_VALID_UNTIL_MARGIN_BOTTOM = 8;
  public static ENCRYPTION_BUTTON_PADDING_TOP = 16;
  public static ENCRYPTION_BUTTON_MARGIN_BOTTOM = 24;
  public static ENCRYPTION_BUTTON_TO_BUTTON_WIDTH = 16;
  public static ENCRYPTION_STAFF_ITEM_MARGIN = 12;
  public static ENCRYPTION_STAFF_ITEM_MARGIN_BOTTOM = 12;
  public static ENCRYPTION_ADD_STAFF_HEIGHT = 28;
  public static ENCRYPTION_ADD_STAFF_BORDER = 1;
  public static ENCRYPTION_ADD_STAFF_BORDER2 = 2;
  public static ENCRYPTION_ADD_STAFF_BORDER_MARGIN_TOP = 8;
  public static ENCRYPTION_SUCCESS_TOGGLE_HEIGHT = 32;
  public static ENCRYPTION_PROTECTION_BUTTON_MARGIN = 8;
  public static ENCRYPTION_PROTECTION_TIME_MENU_PADDING_LEFT = 12;
  public static ENCRYPTION_PROTECTION_TIME_MENU_PADDING_RIGHT = 12;
  public static ENCRYPTION_PROTECTION_TIME_MENU_MARGIN_LEFT = 2;
  public static ENCRYPTION_PROTECTION_TIME_MENU_MARGIN_RIGHT = 2;
  public static ENCRYPTION_ADD_STAFF_FLEX_GROW = 1;
  public static ENCRYPTION_ADD_STAFF_MARGIN_RIGHT = 8;
  public static ENCRYPTION_ADD_STAFF_MARGIN_BOTTOM = 8;
  public static ENCRYPTION_ON_AREA_CHANGE_WIDTH = 0;
  public static ENCRYPTION_DOUBLED_NUMBER = 2;
  public static ENCRYPTION_SET_TIMEOUT_TIME = 20;
  public static ENCRYPTION_EMIT_DIRECTION_STATUS = 1;
  public static ENCRYPTION_ADD_STAFF_LENGTH_MAX = 50;
  public static ENCRYPTION_ADD_STAFF_LENGTH = 0.9;
  public static ENCRYPTION_STATUS_VALUE_COLOR = 0.6;
  public static ENCRYPTION_TYPE_SELECT_INDEX = 0;
  public static ENCRYPTION_TYPE_SELECT = 1;
  public static ENCRYPTION_MESSAGE_DIALOG_TIPS = 400;
  public static ENCRYPTION_MESSAGE_DIALOG_BUTTON = 256;
  public static ENCRYPTION_MESSAGE_DIALOG_TIPS_PADDING = 72;
  public static ENCRYPTION_MESSAGE_ALERT_MESSAGE_TOP = 0;
  public static ENCRYPTION_MESSAGE_ALERT_MESSAGE_TOP1 = 24;
  public static ENCRYPTION_PC_FIXING_WIDTH = 588;
  public static ENCRYPTION_PC_FIXING_STATUS_WIDTH = 400;

  public static DLPRPC_SERVICE_PROXY_ERRCODE = 0;
  public static DLP_MANAGER_BUNDLE_NAME = 'com.ohos.dlpmanager';
  public static DLP_CREDMGR_BUNDLE_NAME = 'com.huawei.hmos.dlpcredmgr';
  public static DLP_CREDMGR_INTERFACE_TOKEN = 'OHOS.HapDlpCredAbilityServiceStub';
  public static DLP_MGR_INTERFACE_TOKEN = 'OHOS.HapDlpMgrAbilityServiceStub';
  public static DLP_PERMISSION_CLEAN_STUB = 'OHOS.HapDlpPermissionAbilityServiceStub';
  public static SA_INTERFACE_TOKEN = 'OHOS.Security.DlpCredentialAbility';
  public static TRANSPARENT_BACKGROUND_COLOR = '#00000000';
  public static START_ABILITY_CUSTOM_CONTENT_DIALOG_WIDTH = 400;
  public static START_ABILITY_CUSTOM_CONTENT_DIALOG_HEIGHT = 125;
  public static START_ABILITY_CUSTOM_CONTENT_MARGIN_BOTTOM = 8;
  public static RATIO_HALF = 0.5;

  public static FOOTER_OPACITY_ONE = 1;
  public static FOOTER_OPACITY_SEPC = 0.6;
  public static FOOTER_OPACITY_MID = 0.5;
  public static readonly ERR_JS_APP_ACCOUNT_INFO = 0;
  public static readonly ERR_JS_APP_INSIDE_ERROR = 1;
  public static readonly ERR_JS_GET_ACCOUNT_ERROR = 2;
  public static readonly ERR_JS_APP_NO_ACCOUNT_ERROR = 3;
  public static readonly ERR_JS_APP_PARAM_ERROR = 4;
  public static readonly ERR_JS_APP_GET_FILE_ASSET_ERROR = 5;
  public static readonly ERR_JS_APP_OPEN_REJECTED = 6;
  public static readonly ERR_JS_APP_ENCRYPTION_REJECTED = 7;
  public static readonly ERR_JS_APP_SYSTEM_IS_AUTHENTICATED = 8;
  public static readonly ERR_JS_APP_NETWORK_INVALID = 9;
  public static readonly ERR_JS_APP_ENCRYPTING = 10;
  public static readonly ERR_JS_APP_CANNOT_OPEN = 11;
  public static readonly ERR_JS_RELEASE_FILE_OPEN = 13
  public static readonly ERR_JS_APP_PERMISSION_DENY = 201;
  public static readonly ERR_JS_CREDENTIAL_TIMEOUT = 19100003;
  public static readonly ERR_JS_CREDENTIAL_SERVICE_ERROR = 19100004;
  public static readonly ERR_JS_CREDENTIAL_SERVER_ERROR = 19100005;
  public static readonly ERR_JS_NOT_DLP_FILE = 19100008;
  public static readonly ERR_JS_DLP_FILE_READ_ONLY = 19100010;
  public static readonly ERR_JS_USER_NO_PERMISSION = 19100013;
  public static readonly ERR_JS_ACCOUNT_NOT_LOGIN = 19100014;
  public static readonly ERR_JS_SYSTEM_NEED_TO_BE_UPGRADED = 19100015;
  public static readonly ERR_JS_NOT_AUTHORIZED_APPLICATION = 19100018;
  public static readonly ERR_JS_FILE_EXPIRATION = 19100019;
  public static readonly ERR_JS_OFFLINE = 19100020;
  public static readonly ERR_JS_NO_SPACE = 19100021;
  public static ERR_JS_INVALID_PARAMETER = 12300002;
  public static ERR_JS_ACCOUNT_NOT_FOUND = 12300003;
  public static ERR_JS_NETWORK_INVALID = 12300013;
  public static ERR_JS_APP_NOT_EXIST = 16000001;
  public static DLP_FILE_PARSE_ERROR = 103;
  public static DLP_INSTALL_SANDBOX_SUCCESS = 202;
  public static DLP_START_SANDBOX_ERROR = 105;
  public static DLP_START_SANDBOX_SUCCESS = 203;
  public static DLP_INSTALL_SANDBOX_ERROR = 104;
  public static ERR_JS_OTHER_APP_OPEN_FILE = 302;

  public static XS_COLUMNS = 2;
  public static XS_SPAN = 2;
  public static XS_OFFSET = 0;
  public static SM_COLUMNS = 4;
  public static SM_SPAN = 4;
  public static SM_OFFSET = 0;
  public static MD_COLUMNS = 8;
  public static MD_SPAN = 8;
  public static MD_OFFSET = 0;
  public static LG_COLUMNS = 12;
  public static LG_OFFSET = 2;

  public static DIALOG_GUTTER = 24;
  public static DIALOG_MD_SPAN = 6;
  public static DIALOG_MD_OFFSET = 1;
  public static DIALOG_LG_SPAN = 6;
  public static DIALOG_LG_OFFSET = 3;
  public static FUSE_PATH = '/mnt/data/fuse/';
  public static RAND_START = 2;
  public static RAND_END = 18;
  public static TYPE_START = 2;
  public static TYPE_END = 3;
  public static BUNDLE_LEN = 20;

  public static DLP_ZIP_MAGIC = 0x04034b50;

  public static VALIDITY_IMAGE_WIDTH = 15;
  public static VALIDITY_IMAGE_HEIGHT = 40;
  public static VALIDITY_IMAGE_PADDING_RIGHT = 12;
  public static VALIDITY_IMAGE_PADDING_LEFT = 8;

  public static TIPS_HEIGHT_ITEM = 20;
  public static TIPS_STAFF_WIDTH = 82;
  public static TIPS_STAFF_MAX_WIDTH = 50;
  public static TIPS_SPACE_ZERO = '\u200B';
  public static TIPS_SPACE_EN = '\u2002';
  public static TIPS_SPACE_EM = '\u2003';
  public static TIPS_NAME_LENGTH = 2;
  public static LOAD_TYPE_CE = 1;

  public static ENTER_KEY_VALUE = '\n';
  public static ENCRYPTION_ADD_STAFF_NO_MARGIN = 0;
  public static RICH_EDITOR_MIN_HEIGHT = 48;
  public static RICH_EDITOR_FIRST = 1;
  public static POPUP_OFFSET_X = -20;
  public static POPUP_OFFSET_RTL_X = 20;
  public static SUB_HEADER_HEIGHT = 40;
  public static SUB_HEADER_WIDTH = '65%';
  public static STAFF_FONT_SIZE = 10;
  public static STAFF_FONT_PADDING = 1;

  // encryptionShare
  public static INTERNATIONAL_DIALING_CODE = '0086';
  public static CONTACTS_PICKER_WIDTH = '100%';
  public static CONTACTS_PICKER_HEIGHT = '100%';
  public static SHARE_TITLE_HEAD_HEIGHT = 56;
  public static SHARE_TITLE_HEAD_MARGIN_TOP = 8;
  public static SHARE_TITLE_HEAD_MARGIN_RIGHT = 16;
  public static SHARE_TITLE_HEAD_MARGIN_BOTTOM = 24;
  public static SHARE_TITLE_HEAD_MARGIN_LEFT = 16;
  public static SHARE_CONTACTS_GROUP_WIDTH = 24;
  public static SHARE_CONTACTS_GROUP_HEIGHT = 24;
  public static SHARE_TEXT_INPUT_HEIGHT = 40;
  public static SHARE_TEXTAREA_MAX_HEIGHT = 188;
  public static SHARE_TEXT_INPUT_CONTENT_PADDING_RIGHT = 32;
  public static SHARE_TEXT_INPUT_CONTENT_PADDING_LEFT = 16;
  public static SHARE_CONTACTS_GROUP_OFFSET_X = -32;
  public static SHARE_CONTACTS_GROUP_OFFSET_X_RTL = 32;
  public static SHARE_CONTACTS_GROUP_OFFSET_Y = 0;
  public static SHARE_TITLE_HEAD_PADDING_LEFT = 16;
  public static SHARE_TEXT_INPUT_MARGIN_RIGHT = 16;
  public static SHARE_TEXT_INPUT_MARGIN_LEFT = 16;
  public static SHARE_TEXT_INPUT_COLUMN_HEIGHT = 120;
  public static SHARE_BUTTON_WIDTH = '100%';
  public static SHARE_BUTTON_MARGIN_LEFT = 16;
  public static SHARE_BUTTON_MARGIN_RIGHT = 16;
  public static SHARE_BUTTON_PADDING_BOTTOM = 16;
  public static SHARE_BUTTON_COLUMN_BOTTOM = 56;
  public static SHARE_PAGES_COLUMN_WIDTH = '100%';
  public static SHARE_PAGES_COLUMN_HEIGHT = '100%';
  public static SHARE_SET_TIMEOUT = 1500;
  public static SHARE_NO_SPACE_LEFT_ON_DEVICE = 13900025;
  public static SHARE_FILE_NAME_TOO_LONG = 13900030;
  public static SHARE_TEMP_SAVE_FILE_NUMBER = 20;
  public static CLEAN_DLP_FILE_IN_CACHE_TIMEOUT: number = 60 * 60 * 1000;

  public static readonly ERR_CODE_NETWORK_ERROR: number = -4;
  public static readonly ERR_CODE_CONNECTION_FAIL: number = -301;
  public static readonly ERR_CODE_CONNECTION_TIME_OUT: number = -310;
  public static readonly ERR_CODE_SUCCESS: number = 0;
  public static readonly COMMAND_SEARCH_USER_INFO = 1;
  public static readonly COMMAND_GET_ACCOUNT_INFO = 2;
  public static readonly COMMAND_GET_DOMAIN_ACCOUNT_INFO = 3;

  public static readonly GET_SETTING_ITEM_XXL1 = 8;
  public static readonly GET_SETTING_ITEM_XXL2 = 18;
  public static readonly GET_SETTING_ITEM_XXL3 = 48;
  public static readonly GET_SETTING_ITEM_DEFAULT = 0;
  public static readonly SYMBOL_GLYPH_FONT_SIZE = 24;

  public static readonly INTERFACE_SUCCESS = 0;
  public static readonly TF_SYNC: number = 0;
  public static readonly TF_ASYNC: number = 1;
}
